name: FSCS
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.6.1
  - matplotlib
  - pandas=1.3.5
  - pip=21.3.1
  - python=3.9.9
  - pytorch=1.10.0
  - regex=2021.7.6
  - torchvision=0.11.0
  - tqdm=4.62.3
  - kaggle=1.5.12
  - setuptools=59.5.0 # <https://github.com/pytorch/pytorch/pull/69904>
  - pip:
    - tensorboard
    - pytorch-transformers==1.2.0
    - pillow
    - gdown
